// generated by volcano.

package es.dmoral.toasty;

public final class R {

    public static final class color {
        public static final int defaultTextColor = _RM.color.defaultTextColor;
        public static final int errorColor = _RM.color.errorColor;
        public static final int infoColor = _RM.color.infoColor;
        public static final int normalColor = _RM.color.normalColor;
        public static final int successColor = _RM.color.successColor;
        public static final int warningColor = _RM.color.warningColor;
    }

    public static final class drawable {
        public static final int ic_check_white_24dp = _RM.drawable.ic_check_white_24dp;
        public static final int ic_clear_white_24dp = _RM.drawable.ic_clear_white_24dp;
        public static final int ic_error_outline_white_24dp = _RM.drawable.ic_error_outline_white_24dp;
        public static final int ic_info_outline_white_24dp = _RM.drawable.ic_info_outline_white_24dp;
        public static final int toast_frame = _RM.drawable.toast_frame;
    }

    public static final class id {
        public static final int toast_icon = _RM.id.toast_icon;
        public static final int toast_root = _RM.id.toast_root;
        public static final int toast_text = _RM.id.toast_text;
    }

    public static final class layout {
        public static final int toast_layout = _RM.layout.toast_layout;
    }

    public static final class string {
        public static final int app_name = _RM.string.app_name;
        public static final int toast_message = _RM.string.toast_message;
    }

    private static final class _RM extends source.SoftwareManagerAndroid.R { }
}
